# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["./id_ecdsa"]
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "docker" do |d|
    #d.image = "sshd-image:latest"
    d.build_dir = "."
    d.has_ssh = true
  end

  # Application server 1
  config.vm.define "app1" do |app1|
    app1.vm.hostname = "app1"
    app1.vm.network "private_network", ip: "192.168.56.4"
  end

  # Application server 2
  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.network "private_network", ip: "192.168.56.5"
  end

  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.6"
  end
end
