---
# Prerequisite:
#
# - Hetzner hcloud API token set in environment variable HCLOUD_TOKEN
#
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create server
      hetzner.hcloud.server:
        state: present
        name: ansible-test
        server_type: "cx22"
        image: centos-stream-10
        location: hel1
        ssh_keys: "stefan@Fangorn.fritz.box"
      register: do

    - name: Add host to our inventory
      add_host:
        hostname: "{{ do.hcloud_server.ipv4_address }}"
        groups: do
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
      when: do.hcloud_server is defined

- hosts: do
  remote_user: root
  gather_facts: False

  tasks:
    - name: Wait for hosts to become reachable
      wait_for_connection:

    - name: Install tcpdump
      package: name=tcpdump state=present
